spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8071
    name: eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false